- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
     - name: Import VPC  output variables
       include_vars: vars/vpc_output.yml
     - name: Import ec2 instances  variables
       include_vars: vars/ec2_variables.yml

     - name: create a key pair
       amazon.aws.ec2_key:
         name: "{{keypair_name}}"
         region: "{{region}}"
         state: "{{state}}"
       register: ansikeyout

     - name: save key in ec2key.pacemaker_cluster:
       state: cleanup # required. choices: cleanup;offline;online;restart. Indicate desired state of the cluster
       node:  # not required. Specify which node of the cluster you want to manage. None == the cluster status itself, 'all' == check the status of all nodes.
       timeout: 300 # not required. Timeout when the module should considered that the action has failed
       force: yes # not required. Force the change of the cluster state