- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
     - name: Import VPC  output variables
       include_vars: vars/vpc_output.yml
     - name: Import ec2 instances  variables
       include_vars: vars/ec2_variables.yml

     - name: create a key pair
       amazon.aws.ec2_key:
         name: "{{keypair_name}}"
         region: "{{region}}"
         state: "{{state}}"
       register: ansikeyout

     - name: save key in ec2keypem
       copy: 
           content: "{{ansikeyout.key.private_key}}"
           dest: "./ec2keypem"
           mode: "{{mode}}"
        when: ansikeyout.changed

     - name: bastionsg security group
       amazon.aws.ec2_security_group:
         name: "{{ bastionsg_name }}"
         description: sg with rule descriptions
         vpc_id: vpc-xxxxxxxx
         profile: "{{ aws_profile }}"
         region: us-east-1
         rules:
            - proto: tcp
              ports:
              - 80
              cidr_ip: 0.0.0.0/0
              rule_desc: allow all on port 80