- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
     - name: Import VPC  output variables
       include_vars: vars/vpc_output.yml
     - name: Import ec2 instances  variables
       include_vars: vars/ec2_variables.yml

     - name: create a key pair
       amazon.aws.ec2_key:
         name: "{{keypair_name}}"
         region: "{{region}}"
         state: "{{state}}"
       register: ansikeyout

     - name: save key in ec2keypem
       copy: 
           content: "{{ansikeyout.key.private_key}}"
           dest: "./ec2keypem"
           mode: 0600
           when: ansikeyout.changed

     - name: bastionsg security group
       amazon.aws.ec2_security_group:
         name: "{{ bastionsg_name }}"
         description: bastionsg with port 22 open
         vpc_id: "{{vpcid}}"
         region: "{{region}}"
         rules:
            - proto: "{{proto}}"
              from_port: "{{from_port1}}"
              to_port: "{{to_port1}}"
              cidr_ip: "{{myip}}"
        register: bastionsgout