- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
     - name: Import VPC variables
       include_vars: vars/vpc_setup.yml
     - name: create my devvpc
       amazon.aws.ec2_vpc_net:
         name: "{{vpc_name}}"
         cidr_block: "{{vpccidr}}"
         region: "{{region}}"
         dns_support:  yes
         dns_hostnames:  yes
         tenancy: default
         state: "{{state}}"
       register: vpcout
     - name: Create pub sub1
       amazon.aws.ec2_vpc_subnet:
         state: "{{state}}"
         vpc_id: "{{vpcout.vpc.id}}"
         cidr: "{{pubsubcidr1}}"
         region: "{{region}}"
         az: "{{az1}}"
         map_public: yes
         tags:
            Name: pubsubnet1
       register: pubsubnet1out
     - name: Create pub sub2
       amazon.aws.ec2_vpc_subnet:
         state: "{{state}}"
         vpc_id: "{{vpcout.vpc.id}}"
         cidr: "{{pubsubcidr2}}"
         region: "{{region}}"
         az: "{{az2}}"
         map_public: yes
         tags:
            Name: pubsubnet2
       register: pubsubnet2out 
     - name: Create pri sub1
       amazon.aws.ec2_vpc_subnet:
         state: "{{state}}"
         vpc_id: "{{vpcout.vpc.id}}"
         cidr: "{{privsubcidr1}}"
         region: "{{region}}"
         az: "{{az1}}"
         tags:
            Name: privbsubnet1
       register: privsubnet1out 
     - name: Create pri sub2
       amazon.aws.ec2_vpc_subnet:
         state: "{{state}}"
         vpc_id: "{{vpcout.vpc.id}}"
         cidr: "{{privsubcidr2}}"
         region: "{{region}}"
         az: "{{az2}}"
         tags:
            Name: privbsubnet2
       register: privsubnet2out 
     - name: Create pri sub3
       amazon.aws.ec2_vpc_subnet:
         state: "{{state}}"
         vpc_id: "{{vpcout.vpc.id}}"
         cidr: "{{privsubcidr3}}"
         region: "{{region}}"
         az: "{{az1}}"
         tags:
            Name: privbsubnet3
       register: privsubnet3out 
     - name: create pri sub4
       amazon.aws.ec2_vpc_subnet:
         state: "{{state}}"
         vpc_id: "{{vpcout.vpc.id}}"
         cidr: "{{privsubcidr4}}"
         region: "{{region}}"
         az: "{{az2}}"
         tags:
            Name: privbsubnet4
       register: privsubnet4out
     - name: Internet gateway
       ec2_vpc_igw:
         vpc_id: "{{vpcout.vpc.id}}"
         state: "{{state}}"
         region: "{{region}}"
         tags:
            Name: dev_igw
       register: igwout
     - name: public  route table
       ec2_vpc_route_table:
          vpc_id: "{{vpcout.vpc.id}}"
          region: "{{region}}"
          tags:
                Name: public_routetable
          subnets:
              - "{{ pubsubnet1out.subnet.id }}"
              - "{{ pubsubnet2out.subnet.id }}"
          routes:
              - dest: 0.0.0.0/0
                gateway_id: "{{ igwout.gateway_id }}"
       register: public_routetableout
     - name: Create  nat gateway1
       ec2_vpc_nat_gateway:
          state: "{{state}}"
          subnet_id: "{{pubsubnet1out.subnet.id}}"
          wait: yes
          if_exist_do_not_create: true
          region: "{{region}}"
       register: nat_gatewayout1
     - name: route table for private sub
       ec2_vpc_route_table:
          vpc_id: "{{vpcout.vpc.id}}"
          region: "{{region}}"
          tags:
              Name: privateroute_table
          subnets:
              - "{{ privsubnet1out.subnet.id }}"
              - "{{ privsubnet2out.subnet.id }}"
              - "{{ privsubnet3out.subnet.id }}"
              - "{{ privsubnet4out.subnet.id }}"
          routes:
              - dest: 0.0.0.0/0
                nat_gateway_id: "{{ nat_gatewayout1.nat_gateway_id }}"
       register: nat_route_tableout
     - set_fact:
             vpcid: "{{vpcout.vpc.id}}"
             pubsubnet1id:  "{{pubsubnet1out.subnet.id}}"
             pubsubnet2id:  "{{pubsubnet2out.subnet.id}}"
             privsubnet1id:  "{{privsubnet1out.subnet.id}}"
             privsubnet2id:  "{{privsubnet2out.subnet.id}}"
             privsubnet3id:  "{{privsubnet3out.subnet.id}}"
             privsubnet4id:  "{{privsubnet4out.subnet.id}}"
             cacheable: yes

     - name: create variable file for vpc output
       copy: 
          content: "vpcid: {{vpcout.vpc.id}}\npubsubnet1id: {{pubsubnet1out.subnet.id}}\n\npubsubnet2id: {{pubsubnet2out.subnet.id}}\nigwid: {{ igwout.gateway_id}}\nprivsubnet1id: {{privsubnet1out.subnet.id}}\nprivsubnet2id: {{privsubnet2out.subnet.id}}\nprivsubnet3id: {{privsubnet3out.subnet.id}}\nprivsubnet4id: {{privsubnet4out.subnet.id}}\n"
          dest: vars/vpc_output.yml