- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
     - name: Import VPC variables
       include_vars: vars/vpc_setup.yml
     - name: create my devvpc
       amazon.aws.ec2_vpc_net:
         name: "{{vpc_name}}"
         cidr_block: "{{vpccidr}}"
         region: "{{region}}"
         dns_support:  yes
         dns_hostnames:  yes
         tenancy: default
         state: "{{state}}"
       register: vpcout
     - name: Create pub sub1
       amazon.aws.ec2_vpc_subnet:
         state: "{{state}}"
         vpc_id: "{{vpcout.vpc.id}}"
         cidr: "{{pubsubcidr1}}"
         region: "{{region}}"
         az: "{{az1}}"
         map_public: yes
         tags:
            Name: pubsubnet1
       register: pubsubnet1out
     - name: Create pub sub2
       amazon.aws.ec2_vpc_subnet:
         state: "{{state}}"
         vpc_id: "{{vpcout.vpc.id}}"
         cidr: "{{pubsubcidr2}}"
         region: "{{region}}"
         az: "{{az2}}"
         map_public: yes
         tags:
            Name: pubsubnet2
       register: pubsubnet2out 
     - name: Create pri sub1
       amazon.aws.ec2_vpc_subnet:
         state: "{{state}}"
         vpc_id: "{{vpcout.vpc.id}}"
         cidr: "{{privsubcidr1}}"
         region: "{{region}}"
         az: "{{az1}}"
         tags:
            Name: privbsubnet1
       register: privsubnet1out 
     - name: Create pri sub2
       amazon.aws.ec2_vpc_subnet:
         state: "{{state}}"
         vpc_id: "{{vpcout.vpc.id}}"
         cidr: "{{privsubcidr2}}"
         region: "{{region}}"
         az: "{{az2}}"
         tags:
            Name: privbsubnet1
       register: privsubnet2out 
     - name: Create pri sub3
       amazon.aws.ec2_vpc_subnet:
         state: "{{state}}"
         vpc_id: "{{vpcout.vpc.id}}"
         cidr: "{{privsubcidr3}}"
         region: "{{region}}"
         az: "{{az1}}"
       register: privsubnet3out 
     - name: create pri sub4
       amazon.aws.ec2_vpc_subnet:
         state: "{{state}}"
         vpc_id: "{{vpcout.vpc.id}}"
         cidr: "{{privsubcidr4}}"
         region: "{{region}}"
         az: "{{az2}}"
       register: privsubnet4out
    
    