- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
     - name: Import VPC mysql_variables:
       variable:  # required. Variable name to operate
       value:  # not required. If set, then sets variable value to this
       login_user:  # not required. The username used to authenticate with.
       login_password:  # not required. The password used to authenticate with.
       login_host: localhost # not required. Host running the database.
       login_port: 3306 # not required. Port of the MySQL server. Requires I(login_host) be defined as other than localhost if login_port is used.
       login_unix_socket:  # not required. The path to a Unix domain socket for local connections.
       connect_timeout: 30 # not required. The connection timeout when connecting to the MySQL server.
       config_file: ~/.my.cnf # not required. Specify a config file from which user and password are to be read.
       ca_cert:  # not required. The path to a Certificate Authority (CA) certificate. This option, if used, must specify the same certificate as used by the server.
       client_cert:  # not required. The path to a client public key certificate.
       client_key:  # not required. The path to the client private key.
