- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
     - name: Import VPC variables
       include_vars: vars/vpc_variables
     - name: create my devvpc
       amazon.aws.ec2_vpc_net:
         name: "{{vpc-name}}"
         cidr_block: "{{vpccidr}}"
         region: "{{region}}"
         dns_support:  yes
         dns_hostname:  yes
         tenancy: default
         state: "{{state}}"
       register: vpc-out
     - name: Create subnet for database servers
       amazon.aws.ec2_vpc_subnet:
       state: present
       vpc_id: "{{vpc}}"
    cidr: 10.0.1.16/28
    tags:
      Name: Database Subnet
  register: database_subnet
